/**
 * Hardware Wallet Daemon API
 * This is the hardware-wallet-daemon API
 *
 * OpenAPI spec version: 0.1.0
 * Contact: steve@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FeaturesResponseDataFeatures { 
    deviceId?: string;
    passphraseProtection: boolean;
    label?: string;
    fwPatch: number;
    fwMajor: number;
    fwMinor: number;
    minorVersion?: number;
    pinProtection: boolean;
    bootloaderHash?: string;
    majorVersion?: number;
    pinCached: boolean;
    vendor: string;
    needsBackup: boolean;
    initialized: boolean;
    model?: string;
    passphraseCached: boolean;
    patchVersion?: number;
}
