/**
 * Hardware Wallet Daemon API
 * This is the hardware-wallet-daemon API
 *
 * OpenAPI spec version: 0.1.0
 * Contact: steve@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransactionSignResponseData { 
    signature?: Array<string>;
}
