language: nodejs

before_script:
- make build_axios_client
- make build_node_client
- make build_tester

script:
- make test_clients
- make docker_build
- make docker_run
- echo 'Running tests from Docker Container'
- cd dev/tester
- node index.js
- exit
- echo 'Done running test from Docker Container'


