language: node_js

node_js:
  - "10.15.1"

before_script:
- make install
- whereis nodejs
- bash .travis/install-linux.sh

script:
- make test
# - make build

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify