// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1WalletTransactionHoursSelection
 */
export interface ApiV1WalletTransactionHoursSelection {
    /**
     * 
     * @type {string}
     * @memberof ApiV1WalletTransactionHoursSelection
     */
    mode?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1WalletTransactionHoursSelection
     */
    shareFactor?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1WalletTransactionHoursSelection
     */
    type?: string;
}

export function ApiV1WalletTransactionHoursSelectionFromJSON(json: any): ApiV1WalletTransactionHoursSelection {
    return {
        'mode': !exists(json, 'mode') ? undefined : json['mode'],
        'shareFactor': !exists(json, 'share_factor') ? undefined : json['share_factor'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function ApiV1WalletTransactionHoursSelectionToJSON(value?: ApiV1WalletTransactionHoursSelection): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'mode': value.mode,
        'share_factor': value.shareFactor,
        'type': value.type,
    };
}


