// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1WalletTransactionWallet
 */
export interface ApiV1WalletTransactionWallet {
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1WalletTransactionWallet
     */
    unspents?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1WalletTransactionWallet
     */
    addresses?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ApiV1WalletTransactionWallet
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1WalletTransactionWallet
     */
    id?: string;
}

export function ApiV1WalletTransactionWalletFromJSON(json: any): ApiV1WalletTransactionWallet {
    return {
        'unspents': !exists(json, 'unspents') ? undefined : json['unspents'],
        'addresses': !exists(json, 'addresses') ? undefined : json['addresses'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function ApiV1WalletTransactionWalletToJSON(value?: ApiV1WalletTransactionWallet): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'unspents': value.unspents,
        'addresses': value.addresses,
        'password': value.password,
        'id': value.id,
    };
}


