// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1WalletsEntries
 */
export interface ApiV1WalletsEntries {
    /**
     * 
     * @type {string}
     * @memberof ApiV1WalletsEntries
     */
    publicKey?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1WalletsEntries
     */
    address?: string;
}

export function ApiV1WalletsEntriesFromJSON(json: any): ApiV1WalletsEntries {
    return {
        'publicKey': !exists(json, 'public_key') ? undefined : json['public_key'],
        'address': !exists(json, 'address') ? undefined : json['address'],
    };
}

export function ApiV1WalletsEntriesToJSON(value?: ApiV1WalletsEntries): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'public_key': value.publicKey,
        'address': value.address,
    };
}


