// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    ApiV1ExplorerAddressOutputs,
    ApiV1ExplorerAddressOutputsFromJSON,
    ApiV1ExplorerAddressOutputsToJSON,
} from './';

/**
 * BlockTransactionVerbose has readable transaction data for transactions inside a block. It differs from Transaction in that it includes metadata for transaction inputs and the calculated coinhour fee spent by the block
 * @export
 * @interface ApiV1PendingTxsTransaction
 */
export interface ApiV1PendingTxsTransaction {
    /**
     * 
     * @type {Array<ApiV1ExplorerAddressOutputs>}
     * @memberof ApiV1PendingTxsTransaction
     */
    outputs?: Array<ApiV1ExplorerAddressOutputs>;
    /**
     * 
     * @type {string}
     * @memberof ApiV1PendingTxsTransaction
     */
    innerHash?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1PendingTxsTransaction
     */
    inputs?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1PendingTxsTransaction
     */
    sigs?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ApiV1PendingTxsTransaction
     */
    length?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1PendingTxsTransaction
     */
    txid?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV1PendingTxsTransaction
     */
    type?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1PendingTxsTransaction
     */
    timestamp?: number;
}

export function ApiV1PendingTxsTransactionFromJSON(json: any): ApiV1PendingTxsTransaction {
    return {
        'outputs': !exists(json, 'outputs') ? undefined : (json['outputs'] as Array<any>).map(ApiV1ExplorerAddressOutputsFromJSON),
        'innerHash': !exists(json, 'inner_hash') ? undefined : json['inner_hash'],
        'inputs': !exists(json, 'inputs') ? undefined : json['inputs'],
        'sigs': !exists(json, 'sigs') ? undefined : json['sigs'],
        'length': !exists(json, 'length') ? undefined : json['length'],
        'txid': !exists(json, 'txid') ? undefined : json['txid'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'timestamp': !exists(json, 'timestamp') ? undefined : json['timestamp'],
    };
}

export function ApiV1PendingTxsTransactionToJSON(value?: ApiV1PendingTxsTransaction): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'outputs': (value.outputs as Array<any>).map(ApiV1ExplorerAddressOutputsToJSON),
        'inner_hash': value.innerHash,
        'inputs': value.inputs,
        'sigs': value.sigs,
        'length': value.length,
        'txid': value.txid,
        'type': value.type,
        'timestamp': value.timestamp,
    };
}


