// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ExplorerAddressStatus
 */
export interface ApiV1ExplorerAddressStatus {
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1ExplorerAddressStatus
     */
    unconfirmed?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ExplorerAddressStatus
     */
    blockSeq?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ExplorerAddressStatus
     */
    label?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1ExplorerAddressStatus
     */
    confirmed?: boolean;
}

export function ApiV1ExplorerAddressStatusFromJSON(json: any): ApiV1ExplorerAddressStatus {
    return {
        'unconfirmed': !exists(json, 'unconfirmed') ? undefined : json['unconfirmed'],
        'blockSeq': !exists(json, 'block_seq') ? undefined : json['block_seq'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'confirmed': !exists(json, 'confirmed') ? undefined : json['confirmed'],
    };
}

export function ApiV1ExplorerAddressStatusToJSON(value?: ApiV1ExplorerAddressStatus): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'unconfirmed': value.unconfirmed,
        'block_seq': value.blockSeq,
        'label': value.label,
        'confirmed': value.confirmed,
    };
}


