// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ExplorerAddressInputs
 */
export interface ApiV1ExplorerAddressInputs {
    /**
     * 
     * @type {string}
     * @memberof ApiV1ExplorerAddressInputs
     */
    owner?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ExplorerAddressInputs
     */
    hours?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1ExplorerAddressInputs
     */
    calculatedHours?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ExplorerAddressInputs
     */
    coins?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ExplorerAddressInputs
     */
    uxid?: string;
}

export function ApiV1ExplorerAddressInputsFromJSON(json: any): ApiV1ExplorerAddressInputs {
    return {
        'owner': !exists(json, 'owner') ? undefined : json['owner'],
        'hours': !exists(json, 'hours') ? undefined : json['hours'],
        'calculatedHours': !exists(json, 'calculated_hours') ? undefined : json['calculated_hours'],
        'coins': !exists(json, 'coins') ? undefined : json['coins'],
        'uxid': !exists(json, 'uxid') ? undefined : json['uxid'],
    };
}

export function ApiV1ExplorerAddressInputsToJSON(value?: ApiV1ExplorerAddressInputs): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'owner': value.owner,
        'hours': value.hours,
        'calculated_hours': value.calculatedHours,
        'coins': value.coins,
        'uxid': value.uxid,
    };
}


