// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ExplorerAddressOutputs
 */
export interface ApiV1ExplorerAddressOutputs {
    /**
     * 
     * @type {number}
     * @memberof ApiV1ExplorerAddressOutputs
     */
    hours?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ExplorerAddressOutputs
     */
    dst?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ExplorerAddressOutputs
     */
    coins?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ExplorerAddressOutputs
     */
    uxid?: string;
}

export function ApiV1ExplorerAddressOutputsFromJSON(json: any): ApiV1ExplorerAddressOutputs {
    return {
        'hours': !exists(json, 'hours') ? undefined : json['hours'],
        'dst': !exists(json, 'dst') ? undefined : json['dst'],
        'coins': !exists(json, 'coins') ? undefined : json['coins'],
        'uxid': !exists(json, 'uxid') ? undefined : json['uxid'],
    };
}

export function ApiV1ExplorerAddressOutputsToJSON(value?: ApiV1ExplorerAddressOutputs): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'hours': value.hours,
        'dst': value.dst,
        'coins': value.coins,
        'uxid': value.uxid,
    };
}


