// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1WalletsMeta
 */
export interface ApiV1WalletsMeta {
    /**
     * 
     * @type {string}
     * @memberof ApiV1WalletsMeta
     */
    filename?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1WalletsMeta
     */
    encrypted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiV1WalletsMeta
     */
    cryptoType?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1WalletsMeta
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1WalletsMeta
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1WalletsMeta
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1WalletsMeta
     */
    coin?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV1WalletsMeta
     */
    timestamp?: number;
}

export function ApiV1WalletsMetaFromJSON(json: any): ApiV1WalletsMeta {
    return {
        'filename': !exists(json, 'filename') ? undefined : json['filename'],
        'encrypted': !exists(json, 'encrypted') ? undefined : json['encrypted'],
        'cryptoType': !exists(json, 'crypto_type') ? undefined : json['crypto_type'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'coin': !exists(json, 'coin') ? undefined : json['coin'],
        'timestamp': !exists(json, 'timestamp') ? undefined : json['timestamp'],
    };
}

export function ApiV1WalletsMetaToJSON(value?: ApiV1WalletsMeta): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'filename': value.filename,
        'encrypted': value.encrypted,
        'crypto_type': value.cryptoType,
        'label': value.label,
        'type': value.type,
        'version': value.version,
        'coin': value.coin,
        'timestamp': value.timestamp,
    };
}


