// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1WalletTransactionTo
 */
export interface ApiV1WalletTransactionTo {
    /**
     * 
     * @type {number}
     * @memberof ApiV1WalletTransactionTo
     */
    hours?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1WalletTransactionTo
     */
    address?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV1WalletTransactionTo
     */
    coins?: number;
}

export function ApiV1WalletTransactionToFromJSON(json: any): ApiV1WalletTransactionTo {
    return {
        'hours': !exists(json, 'hours') ? undefined : json['hours'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'coins': !exists(json, 'coins') ? undefined : json['coins'],
    };
}

export function ApiV1WalletTransactionToToJSON(value?: ApiV1WalletTransactionTo): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'hours': value.hours,
        'address': value.address,
        'coins': value.coins,
    };
}


