// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    ApiV1WalletTransactionHoursSelection,
    ApiV1WalletTransactionHoursSelectionFromJSON,
    ApiV1WalletTransactionHoursSelectionToJSON,
    ApiV1WalletTransactionTo,
    ApiV1WalletTransactionToFromJSON,
    ApiV1WalletTransactionToToJSON,
    ApiV1WalletTransactionWallet,
    ApiV1WalletTransactionWalletFromJSON,
    ApiV1WalletTransactionWalletToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    changeAddress?: string;
    /**
     * 
     * @type {ApiV1WalletTransactionHoursSelection}
     * @memberof InlineObject
     */
    hoursSelection?: ApiV1WalletTransactionHoursSelection;
    /**
     * 
     * @type {boolean}
     * @memberof InlineObject
     */
    ignoreUnconfirmed?: boolean;
    /**
     * 
     * @type {Array<ApiV1WalletTransactionTo>}
     * @memberof InlineObject
     */
    to?: Array<ApiV1WalletTransactionTo>;
    /**
     * 
     * @type {ApiV1WalletTransactionWallet}
     * @memberof InlineObject
     */
    wallet?: ApiV1WalletTransactionWallet;
}

export function InlineObjectFromJSON(json: any): InlineObject {
    return {
        'changeAddress': !exists(json, 'change_address') ? undefined : json['change_address'],
        'hoursSelection': !exists(json, 'hours_selection') ? undefined : ApiV1WalletTransactionHoursSelectionFromJSON(json['hours_selection']),
        'ignoreUnconfirmed': !exists(json, 'ignore_unconfirmed') ? undefined : json['ignore_unconfirmed'],
        'to': !exists(json, 'to') ? undefined : (json['to'] as Array<any>).map(ApiV1WalletTransactionToFromJSON),
        'wallet': !exists(json, 'wallet') ? undefined : ApiV1WalletTransactionWalletFromJSON(json['wallet']),
    };
}

export function InlineObjectToJSON(value?: InlineObject): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'change_address': value.changeAddress,
        'hours_selection': ApiV1WalletTransactionHoursSelectionToJSON(value.hoursSelection),
        'ignore_unconfirmed': value.ignoreUnconfirmed,
        'to': (value.to as Array<any>).map(ApiV1WalletTransactionToToJSON),
        'wallet': ApiV1WalletTransactionWalletToJSON(value.wallet),
    };
}


