// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * Represent unconfirmed transactions
 * @export
 * @interface InlineResponse2003UnconfirmedVerifyTransaction
 */
export interface InlineResponse2003UnconfirmedVerifyTransaction {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2003UnconfirmedVerifyTransaction
     */
    burnFactor?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2003UnconfirmedVerifyTransaction
     */
    maxTransactionSize?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2003UnconfirmedVerifyTransaction
     */
    maxDecimals?: number;
}

export function InlineResponse2003UnconfirmedVerifyTransactionFromJSON(json: any): InlineResponse2003UnconfirmedVerifyTransaction {
    return {
        'burnFactor': !exists(json, 'burn_factor') ? undefined : json['burn_factor'],
        'maxTransactionSize': !exists(json, 'max_transaction_size') ? undefined : json['max_transaction_size'],
        'maxDecimals': !exists(json, 'max_decimals') ? undefined : json['max_decimals'],
    };
}

export function InlineResponse2003UnconfirmedVerifyTransactionToJSON(value?: InlineResponse2003UnconfirmedVerifyTransaction): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'burn_factor': value.burnFactor,
        'max_transaction_size': value.maxTransactionSize,
        'max_decimals': value.maxDecimals,
    };
}


