// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200
     */
    hours?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200
     */
    coins?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    uxid?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    ownerAddress?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200
     */
    spentBlockSeq?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    spentTx?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200
     */
    time?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200
     */
    srcBlockSeq?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    srcTx?: string;
}

export function InlineResponse200FromJSON(json: any): InlineResponse200 {
    return {
        'hours': !exists(json, 'hours') ? undefined : json['hours'],
        'coins': !exists(json, 'coins') ? undefined : json['coins'],
        'uxid': !exists(json, 'uxid') ? undefined : json['uxid'],
        'ownerAddress': !exists(json, 'owner_address') ? undefined : json['owner_address'],
        'spentBlockSeq': !exists(json, 'spent_block_seq') ? undefined : json['spent_block_seq'],
        'spentTx': !exists(json, 'spent_tx') ? undefined : json['spent_tx'],
        'time': !exists(json, 'time') ? undefined : json['time'],
        'srcBlockSeq': !exists(json, 'src_block_seq') ? undefined : json['src_block_seq'],
        'srcTx': !exists(json, 'src_tx') ? undefined : json['src_tx'],
    };
}

export function InlineResponse200ToJSON(value?: InlineResponse200): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'hours': value.hours,
        'coins': value.coins,
        'uxid': value.uxid,
        'owner_address': value.ownerAddress,
        'spent_block_seq': value.spentBlockSeq,
        'spent_tx': value.spentTx,
        'time': value.time,
        'src_block_seq': value.srcBlockSeq,
        'src_tx': value.srcTx,
    };
}


