// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    ApiV1WalletsEntries,
    ApiV1WalletsEntriesFromJSON,
    ApiV1WalletsEntriesToJSON,
    ApiV1WalletsMeta,
    ApiV1WalletsMetaFromJSON,
    ApiV1WalletsMetaToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2005
 */
export interface InlineResponse2005 {
    /**
     * 
     * @type {Array<ApiV1WalletsEntries>}
     * @memberof InlineResponse2005
     */
    entries?: Array<ApiV1WalletsEntries>;
    /**
     * 
     * @type {ApiV1WalletsMeta}
     * @memberof InlineResponse2005
     */
    meta?: ApiV1WalletsMeta;
}

export function InlineResponse2005FromJSON(json: any): InlineResponse2005 {
    return {
        'entries': !exists(json, 'entries') ? undefined : (json['entries'] as Array<any>).map(ApiV1WalletsEntriesFromJSON),
        'meta': !exists(json, 'meta') ? undefined : ApiV1WalletsMetaFromJSON(json['meta']),
    };
}

export function InlineResponse2005ToJSON(value?: InlineResponse2005): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'entries': (value.entries as Array<any>).map(ApiV1WalletsEntriesToJSON),
        'meta': ApiV1WalletsMetaToJSON(value.meta),
    };
}


