// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    InlineResponse2007Data,
    InlineResponse2007DataFromJSON,
    InlineResponse2007DataToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2007
 */
export interface InlineResponse2007 {
    /**
     * 
     * @type {InlineResponse2007Data}
     * @memberof InlineResponse2007
     */
    data?: InlineResponse2007Data;
    /**
     * 
     * @type {any}
     * @memberof InlineResponse2007
     */
    error?: any;
}

export function InlineResponse2007FromJSON(json: any): InlineResponse2007 {
    return {
        'data': !exists(json, 'data') ? undefined : InlineResponse2007DataFromJSON(json['data']),
        'error': !exists(json, 'error') ? undefined : anyFromJSON(json['error']),
    };
}

export function InlineResponse2007ToJSON(value?: InlineResponse2007): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'data': InlineResponse2007DataToJSON(value.data),
        'error': anyToJSON(value.error),
    };
}


