// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2006
 */
export interface InlineResponse2006 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2006
     */
    address?: string;
}

export function InlineResponse2006FromJSON(json: any): InlineResponse2006 {
    return {
        'address': !exists(json, 'address') ? undefined : json['address'],
    };
}

export function InlineResponse2006ToJSON(value?: InlineResponse2006): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'address': value.address,
    };
}


