// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    ApiV1PendingTxsTransaction,
    ApiV1PendingTxsTransactionFromJSON,
    ApiV1PendingTxsTransactionToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2004
 */
export interface InlineResponse2004 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004
     */
    announced?: string;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2004
     */
    isValid?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004
     */
    checked?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2004
     */
    received?: string;
    /**
     * 
     * @type {ApiV1PendingTxsTransaction}
     * @memberof InlineResponse2004
     */
    transaction?: ApiV1PendingTxsTransaction;
}

export function InlineResponse2004FromJSON(json: any): InlineResponse2004 {
    return {
        'announced': !exists(json, 'announced') ? undefined : json['announced'],
        'isValid': !exists(json, 'is_valid') ? undefined : json['is_valid'],
        'checked': !exists(json, 'checked') ? undefined : json['checked'],
        'received': !exists(json, 'received') ? undefined : json['received'],
        'transaction': !exists(json, 'transaction') ? undefined : ApiV1PendingTxsTransactionFromJSON(json['transaction']),
    };
}

export function InlineResponse2004ToJSON(value?: InlineResponse2004): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'announced': value.announced,
        'is_valid': value.isValid,
        'checked': value.checked,
        'received': value.received,
        'transaction': ApiV1PendingTxsTransactionToJSON(value.transaction),
    };
}


