// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    ApiV1ExplorerAddressInputs,
    ApiV1ExplorerAddressInputsFromJSON,
    ApiV1ExplorerAddressInputsToJSON,
    ApiV1ExplorerAddressOutputs,
    ApiV1ExplorerAddressOutputsFromJSON,
    ApiV1ExplorerAddressOutputsToJSON,
    ApiV1ExplorerAddressStatus,
    ApiV1ExplorerAddressStatusFromJSON,
    ApiV1ExplorerAddressStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2002
 */
export interface InlineResponse2002 {
    /**
     * 
     * @type {Array<ApiV1ExplorerAddressOutputs>}
     * @memberof InlineResponse2002
     */
    outputs?: Array<ApiV1ExplorerAddressOutputs>;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002
     */
    innerHash?: string;
    /**
     * 
     * @type {Array<ApiV1ExplorerAddressInputs>}
     * @memberof InlineResponse2002
     */
    inputs?: Array<ApiV1ExplorerAddressInputs>;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2002
     */
    fee?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineResponse2002
     */
    sigs?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2002
     */
    length?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002
     */
    txid?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2002
     */
    type?: number;
    /**
     * 
     * @type {ApiV1ExplorerAddressStatus}
     * @memberof InlineResponse2002
     */
    status?: ApiV1ExplorerAddressStatus;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2002
     */
    timestamp?: number;
}

export function InlineResponse2002FromJSON(json: any): InlineResponse2002 {
    return {
        'outputs': !exists(json, 'outputs') ? undefined : (json['outputs'] as Array<any>).map(ApiV1ExplorerAddressOutputsFromJSON),
        'innerHash': !exists(json, 'inner_hash') ? undefined : json['inner_hash'],
        'inputs': !exists(json, 'inputs') ? undefined : (json['inputs'] as Array<any>).map(ApiV1ExplorerAddressInputsFromJSON),
        'fee': !exists(json, 'fee') ? undefined : json['fee'],
        'sigs': !exists(json, 'sigs') ? undefined : json['sigs'],
        'length': !exists(json, 'length') ? undefined : json['length'],
        'txid': !exists(json, 'txid') ? undefined : json['txid'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'status': !exists(json, 'status') ? undefined : ApiV1ExplorerAddressStatusFromJSON(json['status']),
        'timestamp': !exists(json, 'timestamp') ? undefined : json['timestamp'],
    };
}

export function InlineResponse2002ToJSON(value?: InlineResponse2002): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'outputs': (value.outputs as Array<any>).map(ApiV1ExplorerAddressOutputsToJSON),
        'inner_hash': value.innerHash,
        'inputs': (value.inputs as Array<any>).map(ApiV1ExplorerAddressInputsToJSON),
        'fee': value.fee,
        'sigs': value.sigs,
        'length': value.length,
        'txid': value.txid,
        'type': value.type,
        'status': ApiV1ExplorerAddressStatusToJSON(value.status),
        'timestamp': value.timestamp,
    };
}


