/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiV1WalletsEntries } from './apiV1WalletsEntries';
import { ApiV1WalletsMeta } from './apiV1WalletsMeta';

export class InlineResponse2005 {
    'entries'?: Array<ApiV1WalletsEntries>;
    'meta'?: ApiV1WalletsMeta;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "entries",
            "baseName": "entries",
            "type": "Array<ApiV1WalletsEntries>"
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "ApiV1WalletsMeta"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2005.attributeTypeMap;
    }
}

