/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1WalletTransactionHoursSelection } from './apiV1WalletTransactionHoursSelection';
import { ApiV1WalletTransactionTo } from './apiV1WalletTransactionTo';
import { ApiV1WalletTransactionWallet } from './apiV1WalletTransactionWallet';


export interface InlineObject { 
    changeAddress?: string;
    hoursSelection?: ApiV1WalletTransactionHoursSelection;
    ignoreUnconfirmed?: boolean;
    to?: Array<ApiV1WalletTransactionTo>;
    wallet?: ApiV1WalletTransactionWallet;
}

