/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1WalletsEntries } from './apiV1WalletsEntries';
import { ApiV1WalletsMeta } from './apiV1WalletsMeta';


export interface InlineResponse2005 { 
    entries?: Array<ApiV1WalletsEntries>;
    meta?: ApiV1WalletsMeta;
}

