/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1ExplorerAddressInputs } from './apiV1ExplorerAddressInputs';
import { ApiV1ExplorerAddressOutputs } from './apiV1ExplorerAddressOutputs';
import { ApiV1ExplorerAddressStatus } from './apiV1ExplorerAddressStatus';


export interface InlineResponse2002 { 
    outputs?: Array<ApiV1ExplorerAddressOutputs>;
    innerHash?: string;
    inputs?: Array<ApiV1ExplorerAddressInputs>;
    fee?: number;
    sigs?: Array<string>;
    length?: number;
    txid?: string;
    type?: number;
    status?: ApiV1ExplorerAddressStatus;
    timestamp?: number;
}

