/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BlockVerboseSchemaBody } from './blockVerboseSchemaBody';
import { BlockVerboseSchemaHeader } from './blockVerboseSchemaHeader';


export interface BlockVerboseSchema { 
    header?: BlockVerboseSchemaHeader;
    body?: BlockVerboseSchemaBody;
    size?: number;
}

