/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InlineResponse2005 { 
    /**
     * git branch name
     */
    branch?: string;
    /**
     * git commit id
     */
    commit?: string;
    /**
     * version number
     */
    version?: string;
}

