/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NetworkConnectionSchemaUnconfirmedVerifyTransaction } from './networkConnectionSchemaUnconfirmedVerifyTransaction';


export interface NetworkConnectionSchema { 
    address?: string;
    connectedAt?: number;
    height?: number;
    id?: number;
    isTrustedPeer?: boolean;
    lastReceived?: number;
    lastSent?: number;
    listenPort?: number;
    mirror?: number;
    outgoing?: boolean;
    state?: NetworkConnectionSchema.StateEnum;
    unconfirmedVerifyTransaction?: NetworkConnectionSchemaUnconfirmedVerifyTransaction;
    userAgent?: string;
}
export namespace NetworkConnectionSchema {
    export type StateEnum = 'pending' | 'connected' | 'introduced';
    export const StateEnum = {
        Pending: 'pending' as StateEnum,
        Connected: 'connected' as StateEnum,
        Introduced: 'introduced' as StateEnum
    };
}

