/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiV1PendingTxsTransaction } from './apiV1PendingTxsTransaction';


export interface TransactionEncoded { 
    transaction?: ApiV1PendingTxsTransaction;
    received?: string;
    checked?: string;
    announced?: string;
    isValid?: boolean;
}

