/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionV2ParamsUnspentHoursSelection } from './transactionV2ParamsUnspentHoursSelection';
import { TransactionV2ParamsUnspentTo } from './transactionV2ParamsUnspentTo';


export interface TransactionV2ParamsUnspent { 
    hoursSelection?: TransactionV2ParamsUnspentHoursSelection;
    unspents?: Array<string>;
    changeAddress?: string;
    to?: Array<TransactionV2ParamsUnspentTo>;
}

