/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionStatus } from './transactionStatus';
import { TransactionVerboseTxnInputs } from './transactionVerboseTxnInputs';


/**
 * TransactionVerbose has readable transaction data. It adds TransactionStatus to a BlockTransactionVerbose
 */
export interface TransactionVerboseTxn { 
    status?: TransactionStatus;
    fee?: number;
    innerHash?: string;
    inputs?: Array<TransactionVerboseTxnInputs>;
    length?: number;
    outputs?: Array<object>;
    sigs?: Array<string>;
    timestamp?: number;
    txid?: string;
    type?: number;
}

