/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WalletTransactionRequestHoursSelection } from './walletTransactionRequestHoursSelection';
import { WalletTransactionRequestWallet } from './walletTransactionRequestWallet';


export interface WalletTransactionRequest { 
    changeAddress?: string;
    hoursSelection?: WalletTransactionRequestHoursSelection;
    ignoreUnconfirmed?: boolean;
    to?: Array<object>;
    wallet?: WalletTransactionRequestWallet;
}

