// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1PendingTxsTransactionOutputs
 */
export interface ApiV1PendingTxsTransactionOutputs {
    /**
     * 
     * @type {string}
     * @memberof ApiV1PendingTxsTransactionOutputs
     */
    uxid?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1PendingTxsTransactionOutputs
     */
    dst?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1PendingTxsTransactionOutputs
     */
    coins?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV1PendingTxsTransactionOutputs
     */
    hours?: number;
}

export function ApiV1PendingTxsTransactionOutputsFromJSON(json: any): ApiV1PendingTxsTransactionOutputs {
    return {
        'uxid': !exists(json, 'uxid') ? undefined : json['uxid'],
        'dst': !exists(json, 'dst') ? undefined : json['dst'],
        'coins': !exists(json, 'coins') ? undefined : json['coins'],
        'hours': !exists(json, 'hours') ? undefined : json['hours'],
    };
}

export function ApiV1PendingTxsTransactionOutputsToJSON(value?: ApiV1PendingTxsTransactionOutputs): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'uxid': value.uxid,
        'dst': value.dst,
        'coins': value.coins,
        'hours': value.hours,
    };
}


