// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApiV1PendingTxsTransactionOutputs,
    ApiV1PendingTxsTransactionOutputsFromJSON,
    ApiV1PendingTxsTransactionOutputsToJSON,
} from './';

/**
 * 
 * @export
 * @interface ApiV1PendingTxsTransaction
 */
export interface ApiV1PendingTxsTransaction {
    /**
     * 
     * @type {number}
     * @memberof ApiV1PendingTxsTransaction
     */
    length?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiV1PendingTxsTransaction
     */
    type?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1PendingTxsTransaction
     */
    txid?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1PendingTxsTransaction
     */
    innerHash?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1PendingTxsTransaction
     */
    sigs?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1PendingTxsTransaction
     */
    inputs?: Array<string>;
    /**
     * 
     * @type {Array<ApiV1PendingTxsTransactionOutputs>}
     * @memberof ApiV1PendingTxsTransaction
     */
    outputs?: Array<ApiV1PendingTxsTransactionOutputs>;
}

export function ApiV1PendingTxsTransactionFromJSON(json: any): ApiV1PendingTxsTransaction {
    return {
        'length': !exists(json, 'length') ? undefined : json['length'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'txid': !exists(json, 'txid') ? undefined : json['txid'],
        'innerHash': !exists(json, 'inner_hash') ? undefined : json['inner_hash'],
        'sigs': !exists(json, 'sigs') ? undefined : json['sigs'],
        'inputs': !exists(json, 'inputs') ? undefined : json['inputs'],
        'outputs': !exists(json, 'outputs') ? undefined : (json['outputs'] as Array<any>).map(ApiV1PendingTxsTransactionOutputsFromJSON),
    };
}

export function ApiV1PendingTxsTransactionToJSON(value?: ApiV1PendingTxsTransaction): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'length': value.length,
        'type': value.type,
        'txid': value.txid,
        'inner_hash': value.innerHash,
        'sigs': value.sigs,
        'inputs': value.inputs,
        'outputs': value.outputs === undefined ? undefined : (value.outputs as Array<any>).map(ApiV1PendingTxsTransactionOutputsToJSON),
    };
}


