// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockVerboseSchemaHeader
 */
export interface BlockVerboseSchemaHeader {
    /**
     * 
     * @type {number}
     * @memberof BlockVerboseSchemaHeader
     */
    seq?: number;
    /**
     * 
     * @type {number}
     * @memberof BlockVerboseSchemaHeader
     */
    timestamp?: number;
    /**
     * 
     * @type {number}
     * @memberof BlockVerboseSchemaHeader
     */
    fee?: number;
    /**
     * 
     * @type {number}
     * @memberof BlockVerboseSchemaHeader
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof BlockVerboseSchemaHeader
     */
    blockHash?: string;
    /**
     * 
     * @type {string}
     * @memberof BlockVerboseSchemaHeader
     */
    previousBlockHash?: string;
    /**
     * 
     * @type {string}
     * @memberof BlockVerboseSchemaHeader
     */
    txBodyHash?: string;
    /**
     * 
     * @type {string}
     * @memberof BlockVerboseSchemaHeader
     */
    uxHash?: string;
}

export function BlockVerboseSchemaHeaderFromJSON(json: any): BlockVerboseSchemaHeader {
    return {
        'seq': !exists(json, 'seq') ? undefined : json['seq'],
        'timestamp': !exists(json, 'timestamp') ? undefined : json['timestamp'],
        'fee': !exists(json, 'fee') ? undefined : json['fee'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'blockHash': !exists(json, 'block_hash') ? undefined : json['block_hash'],
        'previousBlockHash': !exists(json, 'previous_block_hash') ? undefined : json['previous_block_hash'],
        'txBodyHash': !exists(json, 'tx_body_hash') ? undefined : json['tx_body_hash'],
        'uxHash': !exists(json, 'ux_hash') ? undefined : json['ux_hash'],
    };
}

export function BlockVerboseSchemaHeaderToJSON(value?: BlockVerboseSchemaHeader): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'seq': value.seq,
        'timestamp': value.timestamp,
        'fee': value.fee,
        'version': value.version,
        'block_hash': value.blockHash,
        'previous_block_hash': value.previousBlockHash,
        'tx_body_hash': value.txBodyHash,
        'ux_hash': value.uxHash,
    };
}


