// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BlockVerboseSchemaBody,
    BlockVerboseSchemaBodyFromJSON,
    BlockVerboseSchemaBodyToJSON,
    BlockVerboseSchemaHeader,
    BlockVerboseSchemaHeaderFromJSON,
    BlockVerboseSchemaHeaderToJSON,
} from './';

/**
 * 
 * @export
 * @interface BlockVerboseSchema
 */
export interface BlockVerboseSchema {
    /**
     * 
     * @type {BlockVerboseSchemaHeader}
     * @memberof BlockVerboseSchema
     */
    header?: BlockVerboseSchemaHeader;
    /**
     * 
     * @type {BlockVerboseSchemaBody}
     * @memberof BlockVerboseSchema
     */
    body?: BlockVerboseSchemaBody;
    /**
     * 
     * @type {number}
     * @memberof BlockVerboseSchema
     */
    size?: number;
}

export function BlockVerboseSchemaFromJSON(json: any): BlockVerboseSchema {
    return {
        'header': !exists(json, 'header') ? undefined : BlockVerboseSchemaHeaderFromJSON(json['header']),
        'body': !exists(json, 'body') ? undefined : BlockVerboseSchemaBodyFromJSON(json['body']),
        'size': !exists(json, 'size') ? undefined : json['size'],
    };
}

export function BlockVerboseSchemaToJSON(value?: BlockVerboseSchema): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'header': BlockVerboseSchemaHeaderToJSON(value.header),
        'body': BlockVerboseSchemaBodyToJSON(value.body),
        'size': value.size,
    };
}


