// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockVerboseSchemaBody
 */
export interface BlockVerboseSchemaBody {
    /**
     * 
     * @type {Array<object>}
     * @memberof BlockVerboseSchemaBody
     */
    txns?: Array<object>;
}

export function BlockVerboseSchemaBodyFromJSON(json: any): BlockVerboseSchemaBody {
    return {
        'txns': !exists(json, 'txns') ? undefined : json['txns'],
    };
}

export function BlockVerboseSchemaBodyToJSON(value?: BlockVerboseSchemaBody): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'txns': value.txns,
    };
}


