// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BlockSchemaBody,
    BlockSchemaBodyFromJSON,
    BlockSchemaBodyToJSON,
    BlockVerboseSchemaHeader,
    BlockVerboseSchemaHeaderFromJSON,
    BlockVerboseSchemaHeaderToJSON,
} from './';

/**
 * 
 * @export
 * @interface BlockSchema
 */
export interface BlockSchema {
    /**
     * 
     * @type {BlockVerboseSchemaHeader}
     * @memberof BlockSchema
     */
    header?: BlockVerboseSchemaHeader;
    /**
     * 
     * @type {BlockSchemaBody}
     * @memberof BlockSchema
     */
    body?: BlockSchemaBody;
    /**
     * 
     * @type {number}
     * @memberof BlockSchema
     */
    size?: number;
}

export function BlockSchemaFromJSON(json: any): BlockSchema {
    return {
        'header': !exists(json, 'header') ? undefined : BlockVerboseSchemaHeaderFromJSON(json['header']),
        'body': !exists(json, 'body') ? undefined : BlockSchemaBodyFromJSON(json['body']),
        'size': !exists(json, 'size') ? undefined : json['size'],
    };
}

export function BlockSchemaToJSON(value?: BlockSchema): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'header': BlockVerboseSchemaHeaderToJSON(value.header),
        'body': BlockSchemaBodyToJSON(value.body),
        'size': value.size,
    };
}


