// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2009
 */
export interface InlineResponse2009 {
    /**
     * 
     * @type {object}
     * @memberof InlineResponse2009
     */
    data?: object;
}

export function InlineResponse2009FromJSON(json: any): InlineResponse2009 {
    return {
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function InlineResponse2009ToJSON(value?: InlineResponse2009): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'data': value.data,
    };
}


