// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2002
 */
export interface InlineResponse2002 {
    /**
     * CurrentCoinHourSupply is coins hours in non distribution addresses.
     * @type {string}
     * @memberof InlineResponse2002
     */
    currentCoinhourSupply?: string;
    /**
     * Coins distributed beyond the project.
     * @type {string}
     * @memberof InlineResponse2002
     */
    currentSupply?: string;
    /**
     * Distribution addresses which are locked and do not count towards total supply.
     * @type {Array<string>}
     * @memberof InlineResponse2002
     */
    lockedDistributionAddresses?: Array<string>;
    /**
     * MaxSupply is the maximum number of coins to be distributed ever.
     * @type {string}
     * @memberof InlineResponse2002
     */
    maxSupply?: string;
    /**
     * TotalCoinHourSupply is coin hours in all addresses including unlocked distribution addresses.
     * @type {string}
     * @memberof InlineResponse2002
     */
    totalCoinhourSupply?: string;
    /**
     * TotalSupply is CurrentSupply plus coins held by the distribution addresses that are spendable.
     * @type {string}
     * @memberof InlineResponse2002
     */
    totalSupply?: string;
    /**
     * Distribution addresses which count towards total supply.
     * @type {Array<string>}
     * @memberof InlineResponse2002
     */
    unlockedDistributionAddresses?: Array<string>;
}

export function InlineResponse2002FromJSON(json: any): InlineResponse2002 {
    return {
        'currentCoinhourSupply': !exists(json, 'current_coinhour_supply') ? undefined : json['current_coinhour_supply'],
        'currentSupply': !exists(json, 'current_supply') ? undefined : json['current_supply'],
        'lockedDistributionAddresses': !exists(json, 'locked_distribution_addresses') ? undefined : json['locked_distribution_addresses'],
        'maxSupply': !exists(json, 'max_supply') ? undefined : json['max_supply'],
        'totalCoinhourSupply': !exists(json, 'total_coinhour_supply') ? undefined : json['total_coinhour_supply'],
        'totalSupply': !exists(json, 'total_supply') ? undefined : json['total_supply'],
        'unlockedDistributionAddresses': !exists(json, 'unlocked_distribution_addresses') ? undefined : json['unlocked_distribution_addresses'],
    };
}

export function InlineResponse2002ToJSON(value?: InlineResponse2002): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'current_coinhour_supply': value.currentCoinhourSupply,
        'current_supply': value.currentSupply,
        'locked_distribution_addresses': value.lockedDistributionAddresses,
        'max_supply': value.maxSupply,
        'total_coinhour_supply': value.totalCoinhourSupply,
        'total_supply': value.totalSupply,
        'unlocked_distribution_addresses': value.unlockedDistributionAddresses,
    };
}


