// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2007
 */
export interface InlineResponse2007 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2007
     */
    address?: string;
}

export function InlineResponse2007FromJSON(json: any): InlineResponse2007 {
    return {
        'address': !exists(json, 'address') ? undefined : json['address'],
    };
}

export function InlineResponse2007ToJSON(value?: InlineResponse2007): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'address': value.address,
    };
}


