// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NetworkConnectionSchema,
    NetworkConnectionSchemaFromJSON,
    NetworkConnectionSchemaToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2004
 */
export interface InlineResponse2004 {
    /**
     * 
     * @type {Array<NetworkConnectionSchema>}
     * @memberof InlineResponse2004
     */
    connections?: Array<NetworkConnectionSchema>;
}

export function InlineResponse2004FromJSON(json: any): InlineResponse2004 {
    return {
        'connections': !exists(json, 'connections') ? undefined : (json['connections'] as Array<any>).map(NetworkConnectionSchemaFromJSON),
    };
}

export function InlineResponse2004ToJSON(value?: InlineResponse2004): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'connections': value.connections === undefined ? undefined : (value.connections as Array<any>).map(NetworkConnectionSchemaToJSON),
    };
}


