// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TransactionEncoded,
    TransactionEncodedFromJSON,
    TransactionEncodedToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2006
 */
export interface InlineResponse2006 {
    /**
     * 
     * @type {Array<TransactionEncoded>}
     * @memberof InlineResponse2006
     */
    transactions?: Array<TransactionEncoded>;
}

export function InlineResponse2006FromJSON(json: any): InlineResponse2006 {
    return {
        'transactions': !exists(json, 'transactions') ? undefined : (json['transactions'] as Array<any>).map(TransactionEncodedFromJSON),
    };
}

export function InlineResponse2006ToJSON(value?: InlineResponse2006): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'transactions': value.transactions === undefined ? undefined : (value.transactions as Array<any>).map(TransactionEncodedToJSON),
    };
}


