// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InlineResponse2008Data,
    InlineResponse2008DataFromJSON,
    InlineResponse2008DataToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2008
 */
export interface InlineResponse2008 {
    /**
     * 
     * @type {InlineResponse2008Data}
     * @memberof InlineResponse2008
     */
    data?: InlineResponse2008Data;
}

export function InlineResponse2008FromJSON(json: any): InlineResponse2008 {
    return {
        'data': !exists(json, 'data') ? undefined : InlineResponse2008DataFromJSON(json['data']),
    };
}

export function InlineResponse2008ToJSON(value?: InlineResponse2008): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'data': InlineResponse2008DataToJSON(value.data),
    };
}


