// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BlockSchema,
    BlockSchemaFromJSON,
    BlockSchemaToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {
    /**
     * 
     * @type {Array<BlockSchema>}
     * @memberof InlineResponse2001
     */
    blocks?: Array<BlockSchema>;
}

export function InlineResponse2001FromJSON(json: any): InlineResponse2001 {
    return {
        'blocks': !exists(json, 'blocks') ? undefined : (json['blocks'] as Array<any>).map(BlockSchemaFromJSON),
    };
}

export function InlineResponse2001ToJSON(value?: InlineResponse2001): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'blocks': value.blocks === undefined ? undefined : (value.blocks as Array<any>).map(BlockSchemaToJSON),
    };
}


