// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2003
 */
export interface InlineResponse2003 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2003
     */
    csrfToken?: string;
}

export function InlineResponse2003FromJSON(json: any): InlineResponse2003 {
    return {
        'csrfToken': !exists(json, 'csrf_token') ? undefined : json['csrf_token'],
    };
}

export function InlineResponse2003ToJSON(value?: InlineResponse2003): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'csrf_token': value.csrfToken,
    };
}


