// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2005
 */
export interface InlineResponse2005 {
    /**
     * git branch name
     * @type {string}
     * @memberof InlineResponse2005
     */
    branch?: string;
    /**
     * git commit id
     * @type {string}
     * @memberof InlineResponse2005
     */
    commit?: string;
    /**
     * version number
     * @type {string}
     * @memberof InlineResponse2005
     */
    version?: string;
}

export function InlineResponse2005FromJSON(json: any): InlineResponse2005 {
    return {
        'branch': !exists(json, 'branch') ? undefined : json['branch'],
        'commit': !exists(json, 'commit') ? undefined : json['commit'],
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function InlineResponse2005ToJSON(value?: InlineResponse2005): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'branch': value.branch,
        'commit': value.commit,
        'version': value.version,
    };
}


