// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NetworkConnectionSchemaUnconfirmedVerifyTransaction,
    NetworkConnectionSchemaUnconfirmedVerifyTransactionFromJSON,
    NetworkConnectionSchemaUnconfirmedVerifyTransactionToJSON,
} from './';

/**
 * 
 * @export
 * @interface NetworkConnectionSchema
 */
export interface NetworkConnectionSchema {
    /**
     * 
     * @type {string}
     * @memberof NetworkConnectionSchema
     */
    address?: string;
    /**
     * 
     * @type {number}
     * @memberof NetworkConnectionSchema
     */
    connectedAt?: number;
    /**
     * 
     * @type {number}
     * @memberof NetworkConnectionSchema
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof NetworkConnectionSchema
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof NetworkConnectionSchema
     */
    isTrustedPeer?: boolean;
    /**
     * 
     * @type {number}
     * @memberof NetworkConnectionSchema
     */
    lastReceived?: number;
    /**
     * 
     * @type {number}
     * @memberof NetworkConnectionSchema
     */
    lastSent?: number;
    /**
     * 
     * @type {number}
     * @memberof NetworkConnectionSchema
     */
    listenPort?: number;
    /**
     * 
     * @type {number}
     * @memberof NetworkConnectionSchema
     */
    mirror?: number;
    /**
     * 
     * @type {boolean}
     * @memberof NetworkConnectionSchema
     */
    outgoing?: boolean;
    /**
     * 
     * @type {string}
     * @memberof NetworkConnectionSchema
     */
    state?: NetworkConnectionSchemaStateEnum;
    /**
     * 
     * @type {NetworkConnectionSchemaUnconfirmedVerifyTransaction}
     * @memberof NetworkConnectionSchema
     */
    unconfirmedVerifyTransaction?: NetworkConnectionSchemaUnconfirmedVerifyTransaction;
    /**
     * 
     * @type {string}
     * @memberof NetworkConnectionSchema
     */
    userAgent?: string;
}

export function NetworkConnectionSchemaFromJSON(json: any): NetworkConnectionSchema {
    return {
        'address': !exists(json, 'address') ? undefined : json['address'],
        'connectedAt': !exists(json, 'connected_at') ? undefined : json['connected_at'],
        'height': !exists(json, 'height') ? undefined : json['height'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'isTrustedPeer': !exists(json, 'is_trusted_peer') ? undefined : json['is_trusted_peer'],
        'lastReceived': !exists(json, 'last_received') ? undefined : json['last_received'],
        'lastSent': !exists(json, 'last_sent') ? undefined : json['last_sent'],
        'listenPort': !exists(json, 'listen_port') ? undefined : json['listen_port'],
        'mirror': !exists(json, 'mirror') ? undefined : json['mirror'],
        'outgoing': !exists(json, 'outgoing') ? undefined : json['outgoing'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'unconfirmedVerifyTransaction': !exists(json, 'unconfirmed_verify_transaction') ? undefined : NetworkConnectionSchemaUnconfirmedVerifyTransactionFromJSON(json['unconfirmed_verify_transaction']),
        'userAgent': !exists(json, 'user_agent') ? undefined : json['user_agent'],
    };
}

export function NetworkConnectionSchemaToJSON(value?: NetworkConnectionSchema): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'address': value.address,
        'connected_at': value.connectedAt,
        'height': value.height,
        'id': value.id,
        'is_trusted_peer': value.isTrustedPeer,
        'last_received': value.lastReceived,
        'last_sent': value.lastSent,
        'listen_port': value.listenPort,
        'mirror': value.mirror,
        'outgoing': value.outgoing,
        'state': value.state,
        'unconfirmed_verify_transaction': NetworkConnectionSchemaUnconfirmedVerifyTransactionToJSON(value.unconfirmedVerifyTransaction),
        'user_agent': value.userAgent,
    };
}

/**
* @export
* @enum {string}
*/
export enum NetworkConnectionSchemaStateEnum {
    Pending = 'pending',
    Connected = 'connected',
    Introduced = 'introduced'
}


