// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Represent unconfirmed transactions
 * @export
 * @interface NetworkConnectionSchemaUnconfirmedVerifyTransaction
 */
export interface NetworkConnectionSchemaUnconfirmedVerifyTransaction {
    /**
     * 
     * @type {number}
     * @memberof NetworkConnectionSchemaUnconfirmedVerifyTransaction
     */
    burnFactor?: number;
    /**
     * 
     * @type {number}
     * @memberof NetworkConnectionSchemaUnconfirmedVerifyTransaction
     */
    maxDecimals?: number;
    /**
     * 
     * @type {number}
     * @memberof NetworkConnectionSchemaUnconfirmedVerifyTransaction
     */
    maxTransactionSize?: number;
}

export function NetworkConnectionSchemaUnconfirmedVerifyTransactionFromJSON(json: any): NetworkConnectionSchemaUnconfirmedVerifyTransaction {
    return {
        'burnFactor': !exists(json, 'burn_factor') ? undefined : json['burn_factor'],
        'maxDecimals': !exists(json, 'max_decimals') ? undefined : json['max_decimals'],
        'maxTransactionSize': !exists(json, 'max_transaction_size') ? undefined : json['max_transaction_size'],
    };
}

export function NetworkConnectionSchemaUnconfirmedVerifyTransactionToJSON(value?: NetworkConnectionSchemaUnconfirmedVerifyTransaction): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'burn_factor': value.burnFactor,
        'max_decimals': value.maxDecimals,
        'max_transaction_size': value.maxTransactionSize,
    };
}


