// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TransactionStatus,
    TransactionStatusFromJSON,
    TransactionStatusToJSON,
    TransactionVerboseTxnInputs,
    TransactionVerboseTxnInputsFromJSON,
    TransactionVerboseTxnInputsToJSON,
} from './';

/**
 * TransactionVerbose has readable transaction data. It adds TransactionStatus to a BlockTransactionVerbose
 * @export
 * @interface TransactionVerboseTxn
 */
export interface TransactionVerboseTxn {
    /**
     * 
     * @type {TransactionStatus}
     * @memberof TransactionVerboseTxn
     */
    status?: TransactionStatus;
    /**
     * 
     * @type {number}
     * @memberof TransactionVerboseTxn
     */
    fee?: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionVerboseTxn
     */
    innerHash?: string;
    /**
     * 
     * @type {Array<TransactionVerboseTxnInputs>}
     * @memberof TransactionVerboseTxn
     */
    inputs?: Array<TransactionVerboseTxnInputs>;
    /**
     * 
     * @type {number}
     * @memberof TransactionVerboseTxn
     */
    length?: number;
    /**
     * 
     * @type {Array<object>}
     * @memberof TransactionVerboseTxn
     */
    outputs?: Array<object>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TransactionVerboseTxn
     */
    sigs?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof TransactionVerboseTxn
     */
    timestamp?: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionVerboseTxn
     */
    txid?: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionVerboseTxn
     */
    type?: number;
}

export function TransactionVerboseTxnFromJSON(json: any): TransactionVerboseTxn {
    return {
        'status': !exists(json, 'status') ? undefined : TransactionStatusFromJSON(json['status']),
        'fee': !exists(json, 'fee') ? undefined : json['fee'],
        'innerHash': !exists(json, 'inner_hash') ? undefined : json['inner_hash'],
        'inputs': !exists(json, 'inputs') ? undefined : (json['inputs'] as Array<any>).map(TransactionVerboseTxnInputsFromJSON),
        'length': !exists(json, 'length') ? undefined : json['length'],
        'outputs': !exists(json, 'outputs') ? undefined : json['outputs'],
        'sigs': !exists(json, 'sigs') ? undefined : json['sigs'],
        'timestamp': !exists(json, 'timestamp') ? undefined : json['timestamp'],
        'txid': !exists(json, 'txid') ? undefined : json['txid'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function TransactionVerboseTxnToJSON(value?: TransactionVerboseTxn): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'status': TransactionStatusToJSON(value.status),
        'fee': value.fee,
        'inner_hash': value.innerHash,
        'inputs': value.inputs === undefined ? undefined : (value.inputs as Array<any>).map(TransactionVerboseTxnInputsToJSON),
        'length': value.length,
        'outputs': value.outputs,
        'sigs': value.sigs,
        'timestamp': value.timestamp,
        'txid': value.txid,
        'type': value.type,
    };
}


