// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionV2ParamsAddressHoursSelection
 */
export interface TransactionV2ParamsAddressHoursSelection {
    /**
     * 
     * @type {string}
     * @memberof TransactionV2ParamsAddressHoursSelection
     */
    type?: string;
}

export function TransactionV2ParamsAddressHoursSelectionFromJSON(json: any): TransactionV2ParamsAddressHoursSelection {
    return {
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function TransactionV2ParamsAddressHoursSelectionToJSON(value?: TransactionV2ParamsAddressHoursSelection): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'type': value.type,
    };
}


