// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TransactionV2ParamsUnspentHoursSelection,
    TransactionV2ParamsUnspentHoursSelectionFromJSON,
    TransactionV2ParamsUnspentHoursSelectionToJSON,
    TransactionV2ParamsUnspentTo,
    TransactionV2ParamsUnspentToFromJSON,
    TransactionV2ParamsUnspentToToJSON,
} from './';

/**
 * 
 * @export
 * @interface TransactionV2ParamsUnspent
 */
export interface TransactionV2ParamsUnspent {
    /**
     * 
     * @type {TransactionV2ParamsUnspentHoursSelection}
     * @memberof TransactionV2ParamsUnspent
     */
    hoursSelection?: TransactionV2ParamsUnspentHoursSelection;
    /**
     * 
     * @type {Array<string>}
     * @memberof TransactionV2ParamsUnspent
     */
    unspents?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TransactionV2ParamsUnspent
     */
    changeAddress?: string;
    /**
     * 
     * @type {Array<TransactionV2ParamsUnspentTo>}
     * @memberof TransactionV2ParamsUnspent
     */
    to?: Array<TransactionV2ParamsUnspentTo>;
}

export function TransactionV2ParamsUnspentFromJSON(json: any): TransactionV2ParamsUnspent {
    return {
        'hoursSelection': !exists(json, 'hours_selection') ? undefined : TransactionV2ParamsUnspentHoursSelectionFromJSON(json['hours_selection']),
        'unspents': !exists(json, 'unspents') ? undefined : json['unspents'],
        'changeAddress': !exists(json, 'change_address') ? undefined : json['change_address'],
        'to': !exists(json, 'to') ? undefined : (json['to'] as Array<any>).map(TransactionV2ParamsUnspentToFromJSON),
    };
}

export function TransactionV2ParamsUnspentToJSON(value?: TransactionV2ParamsUnspent): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'hours_selection': TransactionV2ParamsUnspentHoursSelectionToJSON(value.hoursSelection),
        'unspents': value.unspents,
        'change_address': value.changeAddress,
        'to': value.to === undefined ? undefined : (value.to as Array<any>).map(TransactionV2ParamsUnspentToToJSON),
    };
}


