// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionStatus
 */
export interface TransactionStatus {
    /**
     * If confirmed, the sequence of the block in which the transaction was executed
     * @type {number}
     * @memberof TransactionStatus
     */
    blockSeq?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionStatus
     */
    confirmed?: boolean;
    /**
     * If confirmed, how many blocks deep in the chain it is. Will be at least 1 if confirmed
     * @type {number}
     * @memberof TransactionStatus
     */
    height?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionStatus
     */
    unconfirmed?: boolean;
}

export function TransactionStatusFromJSON(json: any): TransactionStatus {
    return {
        'blockSeq': !exists(json, 'block_seq') ? undefined : json['block_seq'],
        'confirmed': !exists(json, 'confirmed') ? undefined : json['confirmed'],
        'height': !exists(json, 'height') ? undefined : json['height'],
        'unconfirmed': !exists(json, 'unconfirmed') ? undefined : json['unconfirmed'],
    };
}

export function TransactionStatusToJSON(value?: TransactionStatus): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'block_seq': value.blockSeq,
        'confirmed': value.confirmed,
        'height': value.height,
        'unconfirmed': value.unconfirmed,
    };
}


