// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionV2ParamsUnspentTo
 */
export interface TransactionV2ParamsUnspentTo {
    /**
     * 
     * @type {string}
     * @memberof TransactionV2ParamsUnspentTo
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionV2ParamsUnspentTo
     */
    coins?: string;
}

export function TransactionV2ParamsUnspentToFromJSON(json: any): TransactionV2ParamsUnspentTo {
    return {
        'address': !exists(json, 'address') ? undefined : json['address'],
        'coins': !exists(json, 'coins') ? undefined : json['coins'],
    };
}

export function TransactionV2ParamsUnspentToToJSON(value?: TransactionV2ParamsUnspentTo): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'address': value.address,
        'coins': value.coins,
    };
}


