// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApiV1PendingTxsTransaction,
    ApiV1PendingTxsTransactionFromJSON,
    ApiV1PendingTxsTransactionToJSON,
} from './';

/**
 * 
 * @export
 * @interface TransactionEncoded
 */
export interface TransactionEncoded {
    /**
     * 
     * @type {ApiV1PendingTxsTransaction}
     * @memberof TransactionEncoded
     */
    transaction?: ApiV1PendingTxsTransaction;
    /**
     * 
     * @type {string}
     * @memberof TransactionEncoded
     */
    received?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionEncoded
     */
    checked?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionEncoded
     */
    announced?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionEncoded
     */
    isValid?: boolean;
}

export function TransactionEncodedFromJSON(json: any): TransactionEncoded {
    return {
        'transaction': !exists(json, 'transaction') ? undefined : ApiV1PendingTxsTransactionFromJSON(json['transaction']),
        'received': !exists(json, 'received') ? undefined : json['received'],
        'checked': !exists(json, 'checked') ? undefined : json['checked'],
        'announced': !exists(json, 'announced') ? undefined : json['announced'],
        'isValid': !exists(json, 'is_valid') ? undefined : json['is_valid'],
    };
}

export function TransactionEncodedToJSON(value?: TransactionEncoded): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'transaction': ApiV1PendingTxsTransactionToJSON(value.transaction),
        'received': value.received,
        'checked': value.checked,
        'announced': value.announced,
        'is_valid': value.isValid,
    };
}


