// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TransactionV2ParamsAddressHoursSelection,
    TransactionV2ParamsAddressHoursSelectionFromJSON,
    TransactionV2ParamsAddressHoursSelectionToJSON,
} from './';

/**
 * 
 * @export
 * @interface TransactionV2ParamsAddress
 */
export interface TransactionV2ParamsAddress {
    /**
     * 
     * @type {TransactionV2ParamsAddressHoursSelection}
     * @memberof TransactionV2ParamsAddress
     */
    hoursSelection?: TransactionV2ParamsAddressHoursSelection;
}

export function TransactionV2ParamsAddressFromJSON(json: any): TransactionV2ParamsAddress {
    return {
        'hoursSelection': !exists(json, 'hours_selection') ? undefined : TransactionV2ParamsAddressHoursSelectionFromJSON(json['hours_selection']),
    };
}

export function TransactionV2ParamsAddressToJSON(value?: TransactionV2ParamsAddress): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'hours_selection': TransactionV2ParamsAddressHoursSelectionToJSON(value.hoursSelection),
    };
}


