// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TransactionStatus,
    TransactionStatusFromJSON,
    TransactionStatusToJSON,
    TransactionVerboseTxn,
    TransactionVerboseTxnFromJSON,
    TransactionVerboseTxnToJSON,
} from './';

/**
 * 
 * @export
 * @interface TransactionVerbose
 */
export interface TransactionVerbose {
    /**
     * 
     * @type {number}
     * @memberof TransactionVerbose
     */
    time?: number;
    /**
     * 
     * @type {TransactionStatus}
     * @memberof TransactionVerbose
     */
    status?: TransactionStatus;
    /**
     * 
     * @type {TransactionVerboseTxn}
     * @memberof TransactionVerbose
     */
    txn?: TransactionVerboseTxn;
}

export function TransactionVerboseFromJSON(json: any): TransactionVerbose {
    return {
        'time': !exists(json, 'time') ? undefined : json['time'],
        'status': !exists(json, 'status') ? undefined : TransactionStatusFromJSON(json['status']),
        'txn': !exists(json, 'txn') ? undefined : TransactionVerboseTxnFromJSON(json['txn']),
    };
}

export function TransactionVerboseToJSON(value?: TransactionVerbose): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'time': value.time,
        'status': TransactionStatusToJSON(value.status),
        'txn': TransactionVerboseTxnToJSON(value.txn),
    };
}


