// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TransactionStatus,
    TransactionStatusFromJSON,
    TransactionStatusToJSON,
    TransactionTxn,
    TransactionTxnFromJSON,
    TransactionTxnToJSON,
} from './';

/**
 * 
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * 
     * @type {TransactionStatus}
     * @memberof Transaction
     */
    status?: TransactionStatus;
    /**
     * 
     * @type {TransactionTxn}
     * @memberof Transaction
     */
    txn?: TransactionTxn;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    time?: number;
}

export function TransactionFromJSON(json: any): Transaction {
    return {
        'status': !exists(json, 'status') ? undefined : TransactionStatusFromJSON(json['status']),
        'txn': !exists(json, 'txn') ? undefined : TransactionTxnFromJSON(json['txn']),
        'time': !exists(json, 'time') ? undefined : json['time'],
    };
}

export function TransactionToJSON(value?: Transaction): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'status': TransactionStatusToJSON(value.status),
        'txn': TransactionTxnToJSON(value.txn),
        'time': value.time,
    };
}


