// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WalletTransactionRequestHoursSelection
 */
export interface WalletTransactionRequestHoursSelection {
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionRequestHoursSelection
     */
    mode?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionRequestHoursSelection
     */
    shareFactor?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionRequestHoursSelection
     */
    type?: string;
}

export function WalletTransactionRequestHoursSelectionFromJSON(json: any): WalletTransactionRequestHoursSelection {
    return {
        'mode': !exists(json, 'mode') ? undefined : json['mode'],
        'shareFactor': !exists(json, 'share_factor') ? undefined : json['share_factor'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function WalletTransactionRequestHoursSelectionToJSON(value?: WalletTransactionRequestHoursSelection): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'mode': value.mode,
        'share_factor': value.shareFactor,
        'type': value.type,
    };
}


