// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WalletTransactionSignRequest
 */
export interface WalletTransactionSignRequest {
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionSignRequest
     */
    walletId?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionSignRequest
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionSignRequest
     */
    encodedTransaction?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof WalletTransactionSignRequest
     */
    signIndexes?: Array<number>;
}

export function WalletTransactionSignRequestFromJSON(json: any): WalletTransactionSignRequest {
    return {
        'walletId': !exists(json, 'wallet_id') ? undefined : json['wallet_id'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'encodedTransaction': !exists(json, 'encoded_transaction') ? undefined : json['encoded_transaction'],
        'signIndexes': !exists(json, 'sign_indexes') ? undefined : json['sign_indexes'],
    };
}

export function WalletTransactionSignRequestToJSON(value?: WalletTransactionSignRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'wallet_id': value.walletId,
        'password': value.password,
        'encoded_transaction': value.encodedTransaction,
        'sign_indexes': value.signIndexes,
    };
}


