// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WalletTransactionRequestWallet
 */
export interface WalletTransactionRequestWallet {
    /**
     * 
     * @type {Array<string>}
     * @memberof WalletTransactionRequestWallet
     */
    addresses?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionRequestWallet
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionRequestWallet
     */
    password?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WalletTransactionRequestWallet
     */
    unspents?: Array<string>;
}

export function WalletTransactionRequestWalletFromJSON(json: any): WalletTransactionRequestWallet {
    return {
        'addresses': !exists(json, 'addresses') ? undefined : json['addresses'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'unspents': !exists(json, 'unspents') ? undefined : json['unspents'],
    };
}

export function WalletTransactionRequestWalletToJSON(value?: WalletTransactionRequestWallet): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'addresses': value.addresses,
        'id': value.id,
        'password': value.password,
        'unspents': value.unspents,
    };
}


