// tslint:disable
/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    WalletTransactionRequestHoursSelection,
    WalletTransactionRequestHoursSelectionFromJSON,
    WalletTransactionRequestHoursSelectionToJSON,
    WalletTransactionRequestWallet,
    WalletTransactionRequestWalletFromJSON,
    WalletTransactionRequestWalletToJSON,
} from './';

/**
 * 
 * @export
 * @interface WalletTransactionRequest
 */
export interface WalletTransactionRequest {
    /**
     * 
     * @type {string}
     * @memberof WalletTransactionRequest
     */
    changeAddress?: string;
    /**
     * 
     * @type {WalletTransactionRequestHoursSelection}
     * @memberof WalletTransactionRequest
     */
    hoursSelection?: WalletTransactionRequestHoursSelection;
    /**
     * 
     * @type {boolean}
     * @memberof WalletTransactionRequest
     */
    ignoreUnconfirmed?: boolean;
    /**
     * 
     * @type {Array<object>}
     * @memberof WalletTransactionRequest
     */
    to?: Array<object>;
    /**
     * 
     * @type {WalletTransactionRequestWallet}
     * @memberof WalletTransactionRequest
     */
    wallet?: WalletTransactionRequestWallet;
}

export function WalletTransactionRequestFromJSON(json: any): WalletTransactionRequest {
    return {
        'changeAddress': !exists(json, 'change_address') ? undefined : json['change_address'],
        'hoursSelection': !exists(json, 'hours_selection') ? undefined : WalletTransactionRequestHoursSelectionFromJSON(json['hours_selection']),
        'ignoreUnconfirmed': !exists(json, 'ignore_unconfirmed') ? undefined : json['ignore_unconfirmed'],
        'to': !exists(json, 'to') ? undefined : json['to'],
        'wallet': !exists(json, 'wallet') ? undefined : WalletTransactionRequestWalletFromJSON(json['wallet']),
    };
}

export function WalletTransactionRequestToJSON(value?: WalletTransactionRequest): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'change_address': value.changeAddress,
        'hours_selection': WalletTransactionRequestHoursSelectionToJSON(value.hoursSelection),
        'ignore_unconfirmed': value.ignoreUnconfirmed,
        'to': value.to,
        'wallet': WalletTransactionRequestWalletToJSON(value.wallet),
    };
}


