/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiV1WalletTransactionHoursSelection } from './apiV1WalletTransactionHoursSelection';
import { ApiV1WalletTransactionTo } from './apiV1WalletTransactionTo';
import { ApiV1WalletTransactionWallet } from './apiV1WalletTransactionWallet';

export class InlineObject {
    'changeAddress'?: string;
    'hoursSelection'?: ApiV1WalletTransactionHoursSelection;
    'ignoreUnconfirmed'?: boolean;
    'to'?: Array<ApiV1WalletTransactionTo>;
    'wallet'?: ApiV1WalletTransactionWallet;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "changeAddress",
            "baseName": "change_address",
            "type": "string"
        },
        {
            "name": "hoursSelection",
            "baseName": "hours_selection",
            "type": "ApiV1WalletTransactionHoursSelection"
        },
        {
            "name": "ignoreUnconfirmed",
            "baseName": "ignore_unconfirmed",
            "type": "boolean"
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "Array<ApiV1WalletTransactionTo>"
        },
        {
            "name": "wallet",
            "baseName": "wallet",
            "type": "ApiV1WalletTransactionWallet"
        }    ];

    static getAttributeTypeMap() {
        return InlineObject.attributeTypeMap;
    }
}

