/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.26.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class InlineResponse2002 {
    /**
    * CurrentCoinHourSupply is coins hours in non distribution addresses.
    */
    'currentCoinhourSupply'?: string;
    /**
    * Coins distributed beyond the project.
    */
    'currentSupply'?: string;
    /**
    * Distribution addresses which are locked and do not count towards total supply.
    */
    'lockedDistributionAddresses'?: Array<string>;
    /**
    * MaxSupply is the maximum number of coins to be distributed ever.
    */
    'maxSupply'?: string;
    /**
    * TotalCoinHourSupply is coin hours in all addresses including unlocked distribution addresses.
    */
    'totalCoinhourSupply'?: string;
    /**
    * TotalSupply is CurrentSupply plus coins held by the distribution addresses that are spendable.
    */
    'totalSupply'?: string;
    /**
    * Distribution addresses which count towards total supply.
    */
    'unlockedDistributionAddresses'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currentCoinhourSupply",
            "baseName": "current_coinhour_supply",
            "type": "string"
        },
        {
            "name": "currentSupply",
            "baseName": "current_supply",
            "type": "string"
        },
        {
            "name": "lockedDistributionAddresses",
            "baseName": "locked_distribution_addresses",
            "type": "Array<string>"
        },
        {
            "name": "maxSupply",
            "baseName": "max_supply",
            "type": "string"
        },
        {
            "name": "totalCoinhourSupply",
            "baseName": "total_coinhour_supply",
            "type": "string"
        },
        {
            "name": "totalSupply",
            "baseName": "total_supply",
            "type": "string"
        },
        {
            "name": "unlockedDistributionAddresses",
            "baseName": "unlocked_distribution_addresses",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2002.attributeTypeMap;
    }
}

