/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NetworkConnectionSchemaUnconfirmedVerifyTransaction } from './networkConnectionSchemaUnconfirmedVerifyTransaction';

export class NetworkConnectionSchema {
    'address'?: string;
    'connectedAt'?: number;
    'height'?: number;
    'id'?: number;
    'isTrustedPeer'?: boolean;
    'lastReceived'?: number;
    'lastSent'?: number;
    'listenPort'?: number;
    'mirror'?: number;
    'outgoing'?: boolean;
    'state'?: NetworkConnectionSchema.StateEnum;
    'unconfirmedVerifyTransaction'?: NetworkConnectionSchemaUnconfirmedVerifyTransaction;
    'userAgent'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "connectedAt",
            "baseName": "connected_at",
            "type": "number"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "isTrustedPeer",
            "baseName": "is_trusted_peer",
            "type": "boolean"
        },
        {
            "name": "lastReceived",
            "baseName": "last_received",
            "type": "number"
        },
        {
            "name": "lastSent",
            "baseName": "last_sent",
            "type": "number"
        },
        {
            "name": "listenPort",
            "baseName": "listen_port",
            "type": "number"
        },
        {
            "name": "mirror",
            "baseName": "mirror",
            "type": "number"
        },
        {
            "name": "outgoing",
            "baseName": "outgoing",
            "type": "boolean"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "NetworkConnectionSchema.StateEnum"
        },
        {
            "name": "unconfirmedVerifyTransaction",
            "baseName": "unconfirmed_verify_transaction",
            "type": "NetworkConnectionSchemaUnconfirmedVerifyTransaction"
        },
        {
            "name": "userAgent",
            "baseName": "user_agent",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return NetworkConnectionSchema.attributeTypeMap;
    }
}

export namespace NetworkConnectionSchema {
    export enum StateEnum {
        Pending = <any> 'pending',
        Connected = <any> 'connected',
        Introduced = <any> 'introduced'
    }
}
