/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.26.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Represent unconfirmed transactions
*/
export class NetworkConnectionSchemaUnconfirmedVerifyTransaction {
    'burnFactor'?: number;
    'maxDecimals'?: number;
    'maxTransactionSize'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "burnFactor",
            "baseName": "burn_factor",
            "type": "number"
        },
        {
            "name": "maxDecimals",
            "baseName": "max_decimals",
            "type": "number"
        },
        {
            "name": "maxTransactionSize",
            "baseName": "max_transaction_size",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return NetworkConnectionSchemaUnconfirmedVerifyTransaction.attributeTypeMap;
    }
}

