/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.26.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class TransactionV2ParamsUnspentHoursSelection {
    'type'?: string;
    'mode'?: string;
    'shareFactor'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "string"
        },
        {
            "name": "shareFactor",
            "baseName": "share_factor",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TransactionV2ParamsUnspentHoursSelection.attributeTypeMap;
    }
}

