/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.26.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TransactionV2ParamsUnspentHoursSelection } from './transactionV2ParamsUnspentHoursSelection';
import { TransactionV2ParamsUnspentTo } from './transactionV2ParamsUnspentTo';

export class TransactionV2ParamsUnspent {
    'hoursSelection'?: TransactionV2ParamsUnspentHoursSelection;
    'unspents'?: Array<string>;
    'changeAddress'?: string;
    'to'?: Array<TransactionV2ParamsUnspentTo>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "hoursSelection",
            "baseName": "hours_selection",
            "type": "TransactionV2ParamsUnspentHoursSelection"
        },
        {
            "name": "unspents",
            "baseName": "unspents",
            "type": "Array<string>"
        },
        {
            "name": "changeAddress",
            "baseName": "change_address",
            "type": "string"
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "Array<TransactionV2ParamsUnspentTo>"
        }    ];

    static getAttributeTypeMap() {
        return TransactionV2ParamsUnspent.attributeTypeMap;
    }
}

