/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class TransactionVerifyRequest {
    'unsigned'?: boolean;
    'encodedTransaction'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "unsigned",
            "baseName": "unsigned",
            "type": "boolean"
        },
        {
            "name": "encodedTransaction",
            "baseName": "encoded_transaction",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TransactionVerifyRequest.attributeTypeMap;
    }
}

