/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TransactionV2ParamsAddressHoursSelection } from './transactionV2ParamsAddressHoursSelection';

export class TransactionV2ParamsAddress {
    'hoursSelection'?: TransactionV2ParamsAddressHoursSelection;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "hoursSelection",
            "baseName": "hours_selection",
            "type": "TransactionV2ParamsAddressHoursSelection"
        }    ];

    static getAttributeTypeMap() {
        return TransactionV2ParamsAddress.attributeTypeMap;
    }
}

