/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class TransactionStatus {
    /**
    * If confirmed, the sequence of the block in which the transaction was executed
    */
    'blockSeq'?: number;
    'confirmed'?: boolean;
    /**
    * If confirmed, how many blocks deep in the chain it is. Will be at least 1 if confirmed
    */
    'height'?: number;
    'unconfirmed'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "blockSeq",
            "baseName": "block_seq",
            "type": "number"
        },
        {
            "name": "confirmed",
            "baseName": "confirmed",
            "type": "boolean"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "unconfirmed",
            "baseName": "unconfirmed",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return TransactionStatus.attributeTypeMap;
    }
}

