/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class WalletTransactionSignRequest {
    'walletId'?: string;
    'password'?: string;
    'encodedTransaction'?: string;
    'signIndexes'?: Array<number>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "walletId",
            "baseName": "wallet_id",
            "type": "string"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string"
        },
        {
            "name": "encodedTransaction",
            "baseName": "encoded_transaction",
            "type": "string"
        },
        {
            "name": "signIndexes",
            "baseName": "sign_indexes",
            "type": "Array<number>"
        }    ];

    static getAttributeTypeMap() {
        return WalletTransactionSignRequest.attributeTypeMap;
    }
}

