/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface InlineResponse200 {
    "hours"?: number;
    "coins"?: number;
    "uxid"?: string;
    "ownerAddress"?: string;
    "spentBlockSeq"?: number;
    "spentTx"?: string;
    "time"?: number;
    "srcBlockSeq"?: number;
    "srcTx"?: string;
}

