/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface InlineResponse2002 {
    "outputs"?: Array<models.ApiV1ExplorerAddressOutputs>;
    "innerHash"?: string;
    "inputs"?: Array<models.ApiV1ExplorerAddressInputs>;
    "fee"?: number;
    "sigs"?: Array<string>;
    "length"?: number;
    "txid"?: string;
    "type"?: number;
    "status"?: models.ApiV1ExplorerAddressStatus;
    "timestamp"?: number;
}

