/**
 * Skycoin REST API.
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Represent unconfirmed transactions
 */
export interface InlineResponse2003UnconfirmedVerifyTransaction {
    "burnFactor"?: number;
    "maxTransactionSize"?: number;
    "maxDecimals"?: number;
}

